package cmd

import (
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/MeKo-Christian/accessdump/internal/mdb"
	"github.com/spf13/cobra"
)

var (
	schemaRecursive       bool
	schemaFlat            bool
	schemaStrict          bool
	schemaDedupe          bool
	schemaOverwriteReadme bool
)

var schemaCmd = &cobra.Command{
	Use:   "schema [files...]",
	Short: "Extract database schema (DDL + Markdown) from Access files",
	Args:  cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		inputs, err := discoverInputFiles(args, schemaRecursive)
		if err != nil {
			return err
		}

		out := cmd.OutOrStdout()

		if len(inputs) == 0 {
			return errors.New("no .mdb/.accdb files found in inputs")
		}

		baseOut := defaultOutputDir()
		seenHashes := map[string]string{}
		processed, failed := 0, 0

		for _, file := range inputs {
			if schemaDedupe {
				hash, hashErr := computeFileHash(file)
				if hashErr == nil {
					if prev, ok := seenHashes[hash]; ok {
						slog.Default().Debug("skip duplicate", "file", file, "sameAs", prev)
						continue
					}

					seenHashes[hash] = file
				}
			}

			processed++

			schema, loadErr := loadSchema(file)
			if loadErr != nil {
				failed++

				fmt.Fprintf(out, "%s %s: %s\n", colorize("31", "ERROR"), filepath.Base(file), formatCommandError(file, loadErr))

				if schemaStrict {
					return loadErr
				}

				continue
			}

			writeErr := writeSchema(baseOut, file, schema, schemaFlat || format == "flat", schemaOverwriteReadme)
			if writeErr != nil {
				failed++

				fmt.Fprintf(out, "%s %s: %s\n", colorize("31", "ERROR"), filepath.Base(file), formatCommandError(file, writeErr))

				if schemaStrict {
					return writeErr
				}

				continue
			}

			fmt.Fprintf(out, "%s %s -> tables=%d queries=%d relationships=%d\n",
				colorize("32", "OK"), filepath.Base(file),
				len(schema.Tables), len(schema.Queries), len(schema.Relationships))
		}

		fmt.Fprintf(out, "summary: processed=%d failed=%d output=%s\n", processed, failed, baseOut)

		if schemaStrict && failed > 0 {
			return fmt.Errorf("strict mode: %d file(s) failed", failed)
		}

		return nil
	},
}

func loadSchema(path string) (*mdb.Schema, error) {
	db, err := mdb.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open %q: %w", path, err)
	}
	defer db.Close()

	return db.ReadSchema()
}

func writeSchema(baseOutDir, dbPath string, schema *mdb.Schema, flat bool, overwriteReadme bool) error {
	dbName := strings.TrimSuffix(filepath.Base(dbPath), filepath.Ext(dbPath))

	targetDir := baseOutDir
	if !flat {
		targetDir = filepath.Join(baseOutDir, dbName)
	}

	err := os.MkdirAll(targetDir, 0o755)
	if err != nil {
		return fmt.Errorf("create output dir %q: %w", targetDir, err)
	}

	ddl := renderDDL(dbName, schema)

	err = os.WriteFile(filepath.Join(targetDir, dbName+".schema.sql"), []byte(ddl), 0o600)
	if err != nil {
		return err
	}

	md := renderMarkdown(dbName, schema)

	err = os.WriteFile(filepath.Join(targetDir, dbName+".schema.md"), []byte(md), 0o600)
	if err != nil {
		return err
	}

	return writeSchemaReadme(targetDir, dbPath, schema, overwriteReadme)
}

func writeSchemaReadme(targetDir, dbPath string, schema *mdb.Schema, overwrite bool) error {
	readmePath := filepath.Join(targetDir, "README.md")

	if !overwrite {
		if _, err := os.Stat(readmePath); err == nil {
			return nil
		}
	}

	dbName := strings.TrimSuffix(filepath.Base(dbPath), filepath.Ext(dbPath))

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", dbName)
	fmt.Fprintf(&b, "- Source database: %s\n", filepath.Base(dbPath))
	fmt.Fprintf(&b, "- Tables: %d\n", len(schema.Tables))
	fmt.Fprintf(&b, "- Queries: %d\n", len(schema.Queries))
	fmt.Fprintf(&b, "- Relationships: %d\n", len(schema.Relationships))
	fmt.Fprintf(&b, "\nSee [%s.schema.sql](./%s.schema.sql) and [%s.schema.md](./%s.schema.md).\n",
		dbName, dbName, dbName, dbName)

	return os.WriteFile(readmePath, []byte(b.String()), 0o600)
}

func renderDDL(dbName string, s *mdb.Schema) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by accessdump from %s\n\n", dbName)

	for _, table := range s.Tables {
		fmt.Fprintf(&b, "CREATE TABLE %s (\n", quoteIdent(table.Name))

		for i, col := range table.Columns {
			suffix := ","
			if i == len(table.Columns)-1 {
				suffix = ""
			}

			nullable := ""
			if col.Required {
				nullable = " NOT NULL"
			}

			autoInc := ""
			if col.AutoIncrement {
				autoInc = " AUTOINCREMENT"
			}

			fmt.Fprintf(&b, "    %-30s %s%s%s%s\n",
				quoteIdent(col.Name), col.SQLType, nullable, autoInc, suffix)
		}

		fmt.Fprintf(&b, ");\n\n")
	}

	for _, rel := range s.Relationships {
		cascade := ""
		if rel.CascadeUpdate {
			cascade += " ON UPDATE CASCADE"
		}

		if rel.CascadeDelete {
			cascade += " ON DELETE CASCADE"
		}

		fmt.Fprintf(&b, "ALTER TABLE %s\n    ADD CONSTRAINT %s\n    FOREIGN KEY (%s)\n    REFERENCES %s (%s)%s;\n\n",
			quoteIdent(rel.FromTable),
			quoteIdent(rel.Name),
			joinIdents(rel.FromColumns),
			quoteIdent(rel.ToTable),
			joinIdents(rel.ToColumns),
			cascade)
	}

	if len(s.Queries) > 0 {
		fmt.Fprintf(&b, "-- Queries\n\n")

		for _, q := range s.Queries {
			if q.SQL == "" {
				fmt.Fprintf(&b, "-- Query: %s (SQL not available)\n\n", q.Name)
				continue
			}

			trimSQL := strings.TrimSpace(q.SQL)
			if strings.HasPrefix(strings.ToUpper(trimSQL), "SELECT") {
				fmt.Fprintf(&b, "CREATE VIEW %s AS\n%s;\n\n", quoteIdent(q.Name), trimSQL)
			} else {
				// Action queries (INSERT/UPDATE/DELETE) are not valid DDL;
				// emit as SQL comments so the text is preserved but won't execute.
				commented := "-- " + strings.ReplaceAll(trimSQL, "\n", "\n-- ")
				fmt.Fprintf(&b, "-- Action query: %s\n%s;\n\n", q.Name, commented)
			}
		}
	}

	return b.String()
}

func renderMarkdown(dbName string, s *mdb.Schema) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — Schema\n\n", dbName)

	writeTableMarkdown(&b, s.Tables)
	writeRelationshipMarkdown(&b, s.Relationships)
	writeQueryMarkdown(&b, s.Queries)

	return b.String()
}

func writeTableMarkdown(b *strings.Builder, tables []mdb.TableSchema) {
	if len(tables) == 0 {
		return
	}

	fmt.Fprintf(b, "## Tables\n\n")

	for _, table := range tables {
		fmt.Fprintf(b, "### %s\n\n", table.Name)
		fmt.Fprintf(b, "| Column | Type | Size | Required |\n")
		fmt.Fprintf(b, "|---|---|---|---|\n")

		for _, col := range table.Columns {
			size := "—"
			if col.Size > 0 {
				size = strconv.Itoa(col.Size)
			}

			req := ""
			if col.Required {
				req = "✓"
			}

			name := col.Name
			if col.AutoIncrement {
				name += " *(auto)*"
			}

			fmt.Fprintf(b, "| %s | %s | %s | %s |\n", name, col.SQLType, size, req)
		}

		fmt.Fprintf(b, "\n")
	}
}

func writeRelationshipMarkdown(b *strings.Builder, relationships []mdb.Relationship) {
	if len(relationships) == 0 {
		return
	}

	fmt.Fprintf(b, "## Relationships\n\n")

	for _, rel := range relationships {
		cascade := ""
		if rel.CascadeUpdate {
			cascade += " (cascade update)"
		}

		if rel.CascadeDelete {
			cascade += " (cascade delete)"
		}

		fmt.Fprintf(b, "- `%s.%s` → `%s.%s`%s\n",
			rel.FromTable, strings.Join(rel.FromColumns, ", "),
			rel.ToTable, strings.Join(rel.ToColumns, ", "),
			cascade)
	}

	fmt.Fprintf(b, "\n")
}

func writeQueryMarkdown(b *strings.Builder, queries []mdb.QueryDef) {
	if len(queries) == 0 {
		return
	}

	fmt.Fprintf(b, "## Queries\n\n")

	for _, q := range queries {
		fmt.Fprintf(b, "### %s\n\n", q.Name)

		if q.SQL != "" {
			fmt.Fprintf(b, "```sql\n%s\n```\n\n", strings.TrimSpace(q.SQL))
			continue
		}

		fmt.Fprintf(b, "*SQL not available*\n\n")
	}
}

// quoteIdent wraps an identifier in Access-style square brackets.
func quoteIdent(name string) string {
	return "[" + strings.ReplaceAll(name, "]", "]]") + "]"
}

// joinIdents returns a comma-separated list of quoted identifiers.
func joinIdents(names []string) string {
	quoted := make([]string, len(names))
	for i, n := range names {
		quoted[i] = quoteIdent(n)
	}

	return strings.Join(quoted, ", ")
}

func init() {
	rootCmd.AddCommand(schemaCmd)
	schemaCmd.Flags().BoolVar(&schemaRecursive, "recursive", false, "Recursively process directories")
	schemaCmd.Flags().BoolVar(&schemaFlat, "flat", false, "Write files without per-database subdirectory")
	schemaCmd.Flags().BoolVar(&schemaStrict, "strict", false, "Fail on first file error")
	schemaCmd.Flags().BoolVar(&schemaDedupe, "dedupe", false, "Skip duplicate files by content hash")
	schemaCmd.Flags().BoolVar(&schemaOverwriteReadme, "overwrite-readme", false, "Overwrite existing README.md files")
}
